# -*- coding: utf-8 -*-
"""CA_24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_5Dir6-3WxjrHYhcymmjms4xUYnAfTDZ
"""

!pip install qiskit
!pip install qiskit-aer

from qiskit import QuantumCircuit, transpile
from qiskit_aer import Aer

def quantum_fsm(input_signal):
  qc = QuantumCircuit(1, 1)
  if input_signal == 'toggle':
    qc.x(0)
  qc.measure(0, 0)

  simulator = Aer.get_backend('qasm_simulator')
  compiled_circuit = transpile(qc, simulator)

  result = simulator.run(compiled_circuit, shots=1024).result()
  counts = result.get_counts(qc)
  print("Resulting states and their counts:", counts)

quantum_fsm('toggle')